### ISSUE TITLE
dequeueBuffer: BufferQueue has been abandoned

### ISSUE THREAD

**Issue by padi-dev-anhntn** [Banuba/banuba-sdk-flutter#2]
I can't run flutter example project from : https://github.com/Banuba/banuba-sdk-flutter/tree/master/example

Camera not show & all screen is black.

Flutter : 3.10.6
Android : 14

Follow this log : 

`
E/BufferQueueProducer(31857): [SurfaceTexture-0-31857-0](id:7c7100000002,api:1,p:1508,c:31857) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(31857): [SurfaceTexture-0-31857-0](id:7c7100000002,api:1,p:1508,c:31857) dequeueBuffer: BufferQueue has been abandoned
E/OpenGLRenderer(31857): Unable to match the desired swap behavior.
`

**Comment by devsideal** [comment]
Im getting simmilar issue the app getting close just after run,
Im running same example with below config:
Flutter: 3.24.1
Android: 14 

@padi-dev-anhntn how did you get fix this?

**Comment by padi-dev-anhntn** [comment]
@devsideal 
 I was able to run the banuba demo using another repository : https://github.com/Banuba/quickstart-flutter-plugin
